---
title: "Practice 2"
description: |
  Our plan for the second practice
author:
  - name: Travis Gerke
    url: {}
date: 2021-08-21
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Groups

**Dugout 1**

Eliot (1) <br>
Joslyn (1) <br>
Bodey (1) <br>
Merit (1) <br>
James A (2) <br>
Carter G (2) <br>

**Dugout 2**

James P (2) <br>
Colin (2) <br>
Wesley (3) <br>
Carter R (3) <br>
Alexander (3) <br>

### Dynamic warm-up

**Arrival - 8:35**: Catch

**8:35-8:40**: Standard stretching routine led by a player

### Defense

**8:40-9:05**: Fielding in 3 stations (groups below), 8 minutes each.

  1. IF: Rolled grounders from home (not hit with a bat; this improves accuracy and efficiency) + throwing to knock a cone off the top of a tee at 1B from all positions. Rotate through P, C, 2B, SS, 3B. Go through line 5 times at each station. Repeat cycle if time allows.
  2. RF: Pop ups with incrediballs
  3. LF: Long toss to a coach. Gamify this by doing 3 throws each without bouncing, who can get the farthest. Focus on **hard** throws.

### Offense

**9:10-9:50**: Hitting/running in 3 stations, 12 minutes each.

  1. IF: Hitting off machine
  2. Cage: regular BP
  3. CF: HR derby behind net, ideally with second machine if available

### Competition

**9:50-10:20** Scrimmage
