---
title: "About the 8U Brewers"
description: |
  Team philosophy
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Introduction

* Your coaches are Justin Pegg (manager), Travis Gerke, Guy Jackson, and Stu Gornall. We'll also get lots of help from team parents Meraya Pegg and Kristin Bell Gerke.
* Several of us are also members of the league board, so if you have general comments/suggestions for the way the league is run or would like to get involved, reach out!
* We only set two goals each season: 
  1. That every player wants to return next season
  1. That every player is prepared to succeed in the next season, whether this means playing up in 10U or at the next age bracket in 8U
* You'll notice that winning is not one of those goals (which may surprise you if this is not your first season in our highly competitive league). However, we've experienced that a lot of winning naturally occurs as we work towards the two goals -- our teams are consistently very successful. 

### Expectations

* We expect everyone to be here for all practices and games
  + If your child cannot make it for some reason, please let us know in advance
  + We run tightly organized practices and preassign kids to drill groups, so when there are unexpected no-shows it throws things off
  + A parent or guardian must be present for all practices/games
* For field practices, baseball pants and cleats
* For games, arrive 1 hour before start time to warm up
  + This is standard for all teams, but we organize this into a mini-practice
* Minimal feedback during games
  + Players perform best when they are loose. We've seen it often in 8U that, when players are nervous/unsure, mistakes are common
  + For players, please don't try to correct them or let them know about a mistake. We will do this after the game (or later) if we feel a learning opportunity is possible
  + Especially do not comment on umpire performance
* No food/candy in the dugout during games
* Play catch with your kids at home!
  + Our allotted practice times are not sufficient to teach this critical skill
  + We can 100% tell within 3 practices whether kids are getting extra work at home
  + Bonus: you will both cherish this time

### What your child will learn

* How the game works
  + This is the one thing casual observers of our team will recognize: "These kids know what's going on!"
  + It is certainly possible to coach a successful 8U team by barking orders, but we take the alternate route that the kids will be better off learning the game (even if that means making some big mistakes)
* We rotate positions often in practice, but in games, we typically field one or two positions per child over the season
  + Few rotating positions is common in this league, but we have a specific reason for practicing it
  + We don't have enough practice time to teach each of 9 complicated positions. We want to make sure that your child succeeds in their role
* We might teach (or not teach) mechanics a little differently than traditional methods
  + Evidence suggests that, at this age, allowing your child's athleticism to drive success is a more efficient path to progress than constant mechanical adjustment which leads to overthinking
  + We won't allow any obviously detrimental mechanical errors, but probably won't hear us say "Squish the bug, swing level, or hands back"
  + If you want details, Travis has a library of resources he's always happy to share

### Ideal outputs: Hitting

* Swing the bat fast, hit the ball hard (ideally in the air)
  + Give them freedom to find their own mechanical movements that achieve this goal
  + Look at any MLB team: you'll find 9 different swings!
  + Don't emphasize where in the field they should hit it; any hard contact is good
  
### Ideal outputs: Throwing 

* Throw the ball hard (ideally, on target, but a secondary concern)
  + Again, letting the kids find their own mechanical path to achieving this
  + For example, several arm slot variations can be healthy and successful

### Defining success
* We strive to reward effort, not outcomes (and this is very hard for us adults)
  + Easy wins: _run hard, swing hard, throw hard_
  + Example of how parents talk about the game: "Did you win?" "Danny went 4/4!"
  + Example of better ways to recap: "Danny hit the ball to the outfield and had one of the fastest times running to first base."

### Equipment

* Helmet
* Bat: 2' 5/8" max diameter, try to get as light as possible (can make a huge difference). **Must be USA stamped**
* Glove
  + Also a big difference-maker: make sure it's leather and used/broken-in gloves are encouraged. Don't get one too small!
* Cleats: we're going to have them _run_!
* Chest protector / heart guard
* Protective cup

### Coordinating

* We will have a team website in addition to the regular SSU app site
* GameChanger Team Manager -- reach out to us about the live streams
* We will create text message list
* Games begin 9/11
  
### We can always use more help!

* Assistant coaches: you can never have too many at this age
  + There is a compliance process to be completed, and you'll have to wait for a temporary badge to join us on the field
* Help with stat keeping: if interested, talk to Travis
* Snacks after games
  + Need volunteers, Meraya/Kristin will coordinate
* Scorekeeper(s)
  + Required in the book when we are home team
* We will have concession duties, likely twice
* I mentioned in the introductory email about sponsors, so if you know of a business that may be willing to help/wants a banner hung, please let me know
