---
title: "Practice 5"
description: |
  Our plan for the fifth practice
author:
  - name: Travis Gerke
    url: {}
date: 2021-08-31
output:
  distill::distill_article:
    self_contained: false
---

### Groups

**Dugout 1**

Eliot (1) <br>
Joslyn (1) <br>
Bodey (1) <br>
Merit (1) <br>
James A (2) <br>
Carter G (2) <br>

**Dugout 2**

James P (2) <br>
Colin (2) <br>
Wesley (3) <br>
Carter R (3) <br>
AJ (3) <br>

### Dynamic warm-up

**Arrival - 5:35**: Catch

**5:35-5:40**: Standard stretching routine led by a player

### Base running

**5:40-5:45**: Listening to base coaches (Stu on 1B, Justin at 3B). Each kid runs through twice. **Introduce "back" for pop ups, and explain when that can happen** Roll or throw pop-ups to a coach when they run in this section.

**5:45-5:55**: Remove base coaches, explain that kids may now get out. Kids hit. Justin sets up tee at home (with glove to defend at home), Stu left half of IF, Travis right half, Guy 1B

### Defense stations

**6:00-6:24**: Two stations, 8 minutes for first arrangement, 16 minutes for the second. Infield does positional fielding / throwing to first (Stu/Justin). Outfield does mix of pop ups, grounders, and throwing hard back to the coach. Ideal to break outfield into two groups if we can (Guy/Travis).

_Today, Justin will join Group A in their 16 minute outfield time for some running drills_

Group A (infield first, they get rolled grounders and throw to a coach at 1B): Carter R (P), Carter G (2B), Jocelyn (SS), James A (3B), Wes (Rover)

Group B (outfield first): AJ (P), James P (1B), Eliot (2B), Merit (SS), Colin (3B), Bodey (C)

### Offense

**6:25-7:00**: Hitting 3 stations, each kid gets 3 minutes, blow the whistle. Order of stations (as soon as they finish one, go to the back of the line at the next station): infield machine (Travis/Justin), cage (Stu), outfield heavy balls (Guy). Use group numbers at the top of this page for starting positions.

### Scrimmage

**7:00-7:20**: Teams as listed by dugout
